[package]
name = "blockchain"
version = "0.6.1"
authors = ["Wei Tang <hi@that.world>"]
description = "Unopinioned blockchain framework"
license = "GPL-3.0"
edition = "2018"

[dependencies]

[workspace]
members = [
	"network/simple",
	"examples/counter",
]
